'use client';
import { Header } from '@/components/templates/Header';
import { GlobalStyle, theme } from '@/styles';
import type { Metadata } from 'next';
import { Plus_Jakarta_Sans, Poppins } from 'next/font/google';
import { ThemeProvider } from 'styled-components';

const poppins = Poppins({ 
  subsets: ['latin'],
  weight: ['500', '600', '700'],
  variable: '--font-poppins',
})

const jakarta = Plus_Jakarta_Sans({ 
  subsets: ['latin'],
  weight: ['500', '600', '700'],
  variable: '--font-jakarta',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
        <body className={`${poppins.variable} ${jakarta.variable}`}>
          <ThemeProvider theme={{theme}}>
              <GlobalStyle />
              <Header />
              {children}
          </ThemeProvider>
        </body>
    </html>
  )
}
